pull_request_rules:
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
  - name: automatic merge for scala-steward pull requests affecting build.sbt
    conditions:
      - author=scala-steward
      - check-success=ci-2-12
      - check-success=ci-2-13
      - "#files=1"
      - files=build.sbt
    actions:
      merge:
        method: merge
  - name: automatic merge for scala-steward pull requests affecting project plugins.sbt
    conditions:
      - author=scala-steward
      - check-success=ci-2-12
      - check-success=ci-2-13
      - "#files=1"
      - files=project/plugins.sbt
    actions:
      merge:
        method: merge
  - name: automatic merge for scala-steward pull requests affecting project build.properties
    conditions:
      - author=scala-steward
      - check-success=ci-2-12
      - check-success=ci-2-13
      - "#files=1"
      - files=project/build.properties
    actions:
      merge:
        method: merge
  - name: semi-automatic merge for scala-steward pull requests
    conditions:
      - author=scala-steward
      - check-success=ci-2-12
      - check-success=ci-2-13
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: automatic merge for scala-steward pull requests affecting .scalafmt.conf
    conditions:
      - author=scala-steward
      - check-success=ci-2-12
      - check-success=ci-2-13
      - "#files=1"
      - files=.scalafmt.conf
    actions:
      merge:
        method: merge
